apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
spec:
  selector:
    prometheus: kube-prometheus-prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30000  # Choose an available node por
  type: NodePort
