apiVersion: v1
kind: Service
metadata:
  name: worker-service
  labels:
    job: worker-api
    app: worker
spec:
  type: NodePort
  ports:
    - name: web
      port: 5000
      targetPort: 5000
      nodePort: 30005  # Specify the desired node port
  selector:
    app: worker

